"""Clean-room core contracts for the rebuilt Insight Desk engine."""

from .canonical_v2 import (
    AuthoritativeFact,
    CanonicalEvidenceRef,
    CanonicalEvent,
    CanonicalPublicationBundle,
    SourceDocument,
    VerifiedPublication,
)
from .contracts import (
    CandidateEvent,
    Certainty,
    ContractBundle,
    ContractError,
    EvidenceField,
    EvidenceSpan,
    EventFact,
    OutcomePolarity,
    RawArticle,
    RenderMode,
    RenderedBriefing,
    RenderedEntry,
    SourceProvenance,
    TemporalState,
    VerificationCheck,
    VerificationVerdict,
    VerifiedClaim,
)
from .event_understanding_port_v2 import (
    EventUnderstandingPort,
    EventUnderstandingRequest,
    validate_understanding_result,
)
from .event_understanding_v2 import (
    ArticleEventRole,
    ArticleUnderstanding,
    CanonicalEventDraft,
    TopicRelation,
    UnderstandingEvidenceField,
    UnderstandingEvidenceRef,
    UnderstandingStatus,
    canonical_event_from_draft,
)
from .failure_policy import FailureKind, PipelineStage, RecoveryAction, recovery_action
from .identity import (
    IdentityDecision,
    IdentityKey,
    IdentityPrecheck,
    IdentityPrecheckVerdict,
    finalize_identity,
    precheck_identity,
)
from .orchestration_v2 import (
    OWNER_BOUNDARIES,
    OwnerBoundary,
    PipelineResponsibility,
    owner_for,
    validate_owner_boundaries,
)
from .relevance import (
    RelevanceDecision,
    RelevanceReason,
    RelevanceVerdict,
    relevance_from_literal_match,
)
from .selection import (
    SelectionDecision,
    SelectionReason,
    SelectionSignals,
    SelectionVerdict,
    decide_selection,
)
from .verification import VerificationPolicy, aggregate_verdict

__all__ = [
    "ArticleEventRole",
    "ArticleUnderstanding",
    "AuthoritativeFact",
    "CandidateEvent",
    "CanonicalEvidenceRef",
    "CanonicalEvent",
    "CanonicalEventDraft",
    "CanonicalPublicationBundle",
    "Certainty",
    "ContractBundle",
    "ContractError",
    "EventUnderstandingPort",
    "EventUnderstandingRequest",
    "EvidenceField",
    "EvidenceSpan",
    "EventFact",
    "FailureKind",
    "IdentityDecision",
    "IdentityKey",
    "IdentityPrecheck",
    "IdentityPrecheckVerdict",
    "OWNER_BOUNDARIES",
    "OutcomePolarity",
    "OwnerBoundary",
    "PipelineResponsibility",
    "PipelineStage",
    "RawArticle",
    "RecoveryAction",
    "RelevanceDecision",
    "RelevanceReason",
    "RelevanceVerdict",
    "RenderMode",
    "RenderedBriefing",
    "RenderedEntry",
    "SelectionDecision",
    "SelectionReason",
    "SelectionSignals",
    "SelectionVerdict",
    "SourceDocument",
    "SourceProvenance",
    "TemporalState",
    "TopicRelation",
    "UnderstandingEvidenceField",
    "UnderstandingEvidenceRef",
    "UnderstandingStatus",
    "VerificationCheck",
    "VerificationPolicy",
    "VerificationVerdict",
    "VerifiedClaim",
    "VerifiedPublication",
    "aggregate_verdict",
    "canonical_event_from_draft",
    "decide_selection",
    "finalize_identity",
    "owner_for",
    "precheck_identity",
    "recovery_action",
    "relevance_from_literal_match",
    "validate_owner_boundaries",
    "validate_understanding_result",
]